#!/bin/bash

# Array of commit messages for UI improvements
commits=(
  "style(css): add hover transition effects to buttons"
  "style(css): improve card shadow on hover state"
  "style(css): add smooth scrolling behavior"
  "style(css): update scrollbar styling for webkit"
  "style(css): add focus ring styles for accessibility"
  "style(css): improve text selection highlighting"
  "feat(ui): add ripple effect animation keyframes"
  "style(css): update gradient text effect"
  "style(css): add glass morphism backdrop blur"
  "style(css): improve border radius consistency"
  "feat(animation): add fade-in animation utility"
  "feat(animation): add slide-up animation utility"
  "feat(animation): add scale-in animation utility"
  "style(css): improve button active states"
  "style(css): add button disabled styles"
  "feat(ui): add pulse animation for notifications"
  "style(css): update input field focus styles"
  "style(css): add form validation styles"
  "feat(animation): add bounce animation utility"
  "style(css): improve link hover underline effect"
  "style(css): add card content padding adjustments"
  "feat(ui): add loading skeleton animation"
  "style(css): update typography line heights"
  "style(css): improve heading font weights"
  "feat(animation): add rotate animation utility"
  "style(css): add responsive font sizes"
  "style(css): improve mobile touch targets"
  "feat(ui): add shimmer loading effect"
  "style(css): update modal overlay backdrop"
  "style(css): add dropdown shadow styles"
  "feat(animation): add wave animation utility"
  "style(css): improve alert component styles"
  "style(css): add success state color variables"
  "style(css): add error state color variables"
  "style(css): add warning state color variables"
  "feat(ui): add glow effect utility class"
  "style(css): update badge component styles"
  "style(css): improve tooltip arrow styles"
  "feat(animation): add float animation for icons"
  "style(css): add avatar ring styles"
  "style(css): update progress bar animations"
  "feat(ui): add gradient border utility"
  "style(css): improve tab active indicator"
  "style(css): add switch toggle transitions"
  "feat(animation): add shake animation for errors"
  "style(css): update checkbox custom styles"
  "style(css): add radio button custom styles"
  "feat(ui): add confetti animation keyframes"
  "style(css): improve dropdown item hover"
  "style(css): add menu divider styles"
  "feat(animation): add spin animation utility"
  "style(css): update toast notification styles"
  "style(css): add breadcrumb separator styles"
  "feat(ui): add parallax scroll effect"
  "style(css): improve footer link spacing"
  "style(css): add social icon hover effects"
  "feat(animation): add zoom animation utility"
  "style(css): update pagination button styles"
  "style(css): add stepper component styles"
  "feat(ui): add morphing shape animation"
  "style(css): improve carousel indicator styles"
  "style(css): add lightbox overlay styles"
  "feat(animation): add swing animation utility"
  "style(css): update accordion expand styles"
  "style(css): add collapsible panel transitions"
  "feat(ui): add gradient mesh background"
  "style(css): improve chip component styles"
  "style(css): add tag removal button styles"
  "feat(animation): add heartbeat animation"
  "style(css): update file upload dropzone"
  "style(css): add image gallery grid styles"
  "feat(ui): add particle effect keyframes"
  "style(css): improve date picker styles"
  "style(css): add time picker transitions"
  "chore(cleanup): optimize CSS bundle size"
  "docs(css): add inline documentation comments"
)

# Update globals.css with small additions for each commit
for i in "${!commits[@]}"; do
  # Add a CSS comment with incremental improvements
  echo "" >> frontend/src/app/globals.css
  echo "/* UI Enhancement #$((i+1)): ${commits[$i]} */" >> frontend/src/app/globals.css
  
  git add frontend/src/app/globals.css
  git commit -m "${commits[$i]}"
done

echo "Generated ${#commits[@]} commits"
